# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b55e25baa7f26e1f79d273ce5b5ddb00a31ef84e5c1a9acd6da66f197a631e6ffa9958885f326081f2a5f289c70617a1b7d77fcd627cb55a0ac110e58beedf9

test:
  secret_key_base: aaf04a70f4376dac32101d2f582a706edbc71ea28e0b745bb9fa3a60eca39513b806810fed5e9a7b1fd1db3350027deb54a0e085db532b4c69e7bb544c75d1c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
